# Generated by Django 4.1.2 on 2022-12-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("about", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("email", models.CharField(max_length=200, unique=True)),
                ("message", models.TextField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("image2", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
            ],
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("title", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("about", models.CharField(max_length=200)),
            ],
        ),
    ]
