# Generated by Django 3.2.16 on 2023-01-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_instructor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
